<?php

return [
    'bigIncrements' => 'number',
    'bigInteger' => 'number',
    'boolean' => 'switch',
    'char' => 'text',
    'date' => 'date',
    'dateTime' => 'datetime',
    'dateTimeTz' => 'datetime',
    'decimal' => 'currency',
    'double' => 'currency',
    'float' => 'currency',
    'geometry' => 'text',
    'geometryCollection' => 'text',
    'increments' => 'number',
    'integer' => 'number',
    'ipAddress' => 'ip',
    'json' => 'text',
    'jsonb' => 'text',
    'longText' => 'summernote',
    'smallIncrements' => 'number',
    'smallInteger' => 'number',
    'string' => 'text',
    'text' => 'summernote',
    'time' => 'time',
    'timeTz' => 'time',
    'timestamp' => 'text',
    'timestampTz' => 'text',
    'tinyIncrements' => 'number',
    'tinyInteger' => 'number',
    'unsignedBigInteger' => 'number',
    'unsignedDecimal' => 'currency',
    'unsignedInteger' => 'number',
    'unsignedSmallInteger' => 'number',
    'unsignedTinyInteger' => 'number',
    'uuid' => 'text',
    'year' => 'text',
];